### ISSUE TITLE
Something goes wrong when pulling `settingsOptions` at commit `ae4ba`

### ISSUE THREAD

**Issue by aalok-sathe** [evlabwebapps/sentspace-web#1]
https://github.com/evlabwebapps/sentspace-web/blob/ae4ba35ea769104c66596c992be9a567e57f6651/src/components/ComputeForm.jsx#L46

```jsx
ComputeForm.jsx:46 Uncaught TypeError: settingsOptions.map is not a function
    at ComputeForm.jsx:46:1
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070:1)
    at executeDispatch (react-dom.development.js:8243:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8275:1)
    at processDispatchQueue (react-dom.development.js:8288:1)
    at dispatchEventsForPlugins (react-dom.development.js:8299:1)
    at react-dom.development.js:8508:1
```

**Comment by aalok-sathe** [comment]
Fixed in [abcb445](https://github.com/evlabwebapps/sentspace-web/commit/abcb44582d120aa62b332d2e0b540a32f056faa5)
